CREATE TABLE MEMBER(
	MID VARCHAR(20) PRIMARY KEY,
	PASSWORD VARCHAR(20) NOT NULL,
	NAME VARCHAR(30) NOT NULL,
	ROLE VARCHAR(10) DEFAULT 'USER'
);

SELECT * FROM MEMBER;
INSERT INTO MEMBER(MID,PASSWORD,NAME,ROLE) VALUES('admin','1234','관리자','ADMIN');
INSERT INTO MEMBER(MID,PASSWORD,NAME) VALUES('jaeho','1234','제호');
DROP TABLE MEMBER;

