CREATE TABLE PRODUCT(
	NUM INT PRIMARY KEY,
	NAME VARCHAR(50) NOT NULL,
	DETAILS VARCHAR(100),
	PRICE INT,
	CNT INT,
	SELLER VARCHAR(20) --FK 외래키 외부키 =MID VARCHAR(20) PRIMARY KEY
);

INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'사이다','톡쏘는 칠성사이다',1200,5,'admin');
INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'콜라','톡쏘는 코카콜라',1300,2,'admin');
INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'망고스무디','달달한 망고 스무디',3800,0,'admin');
INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'카페라떼','씁쓸한 카페라뗴',1800,20,'admin');
INSERT INTO PRODUCT VALUES((SELECT NVL(MAX(NUM),0)+1 FROM PRODUCT),'아메리카노','고소한 아메리카노',2800,30,'admin');


ALTER TABLE PRODUCT
ADD CONSTRAINT FK_SELLER
FOREIGN KEY (SELLER)
REFERENCES MEMBER(MID)
ON DELETE SET NULL;

DROP TABLE PRODUCT;

SELECT P.NUM, P.NAME, P.DETAILS, P.PRICE, P.CNT, M.NAME AS SELLER FROM PRODUCT P JOIN MEMBER M ON P.SELLER = M.MID;
--1. Id >> NAME
--2. FK 제약조건 ALTER 추가
--3. DTO 멤버변수 추가
--4. DAO SQL문 JOIN 사용
--5. 예외처리 